version: '3.8'

services:
  atlas:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: local-atlas:latest
    command: ["npm", "start" ]
    ports:
      - "80:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
       - .:/src/